### ISSUE TITLE
#### Fontend/Backend Problem - WebSocket Error 

### ISSUE THREAD

**Issue by Self-Mark-King** [Self-Mark-King/django-drf-react-todo#2]
I have a working frontend and backend that worked locally but not when deployed to heroku
- [x] Redo frontend
- [x ] Websocket error on yarn start

This is a package error:
see https://github.com/facebook/create-react-app/pull/8079
Change  > node_modules/react-dev-utils/webpackHotDevClient.js
on line 62 to > protocol: window.location.protocol === 'https:' ? 'wss' : 'ws',

Thanks @yuki, @Korey

**Comment by geekwise-korey-nichols** [comment]
@geekwise-Jesus-Garcia had the same issue yesterday. I don't know how to fix it. He might know what to do

**Comment by climateamante** [comment]
@Self-Mark-King I would asking @geekwise-ashkan-nadiri and @geekwise-estefania-flores
They both have worked past this specific challenge and would have a piece of code to reference.

I am going to tag them in a new issue on the main project board for them.

**Comment by Self-Mark-King** [comment]
Issue closed after package issued resolved
